### ISSUE TITLE
create WebHook not working

### ISSUE THREAD

**Issue by negosolutions** [ajimix/asana-api-php-class#62]
Hi guys!
I have successfully used this script times before but now I need to create a webhook and it simply would not authorize me for the exact same access token I use to pull a task, which works:. SO I am able to get details on a task, but when I try to create a webhook I get a 400 error :(

I am using this test file to post to the request file and the handshake header is ok: https://superwpheroes.io/wp-content/themes/NEGOSOL/_framework/lib/ns-agency-manager/core/integrations/asana/asana-api-php-class-master/examples/testpost.php

I am using this code to actually try and create the webhook:

<?php
require_once('../asana.php');
$asana = new Asana(array('personalAccessToken' => 'xxxxxx'));

$target = 'https://superwpheroes.io/wp-content/themes/NEGOSOL/_framework/lib/ns-agency-manager/core/integrations/asana/asana-api-php-class-master/examples/test.php';
$workspaceId = 1234;

$asana->createWebhook($workspaceId, $target);

if ($asana->hasError()) {
    echo 'Error while trying to connect to Asana, response code: ' . $asana->responseCode;
    exit;
}
?>

it gives of a 400 unauthorized error no matter what, though a 400 error is consistent of a malformed request.

obviously, trying to get a webhook returns no results :(

I have a valid SSL, outgoing connections are not blocked... not sure what else to try really :(
Of course, the access token and workspace ID are masked out here, but this is the debug info I get:

Array
(
    [url] => https://app.asana.com/api/1.0/webhooks
    [content_type] => 
    [http_code] => 400
    [header_size] => 0
    [request_size] => 241
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 1.11194
    [namelookup_time] => 0.031051
    [connect_time] => 0.052622
    [pretransfer_time] => 0.279585
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 1.111918
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 52.1.223.154
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 170.10.161.106
    [local_port] => 36392
    [request_header] => GET /api/1.0/webhooks HTTP/1.1
Host: app.asana.com
Accept: */*
Authorization: Bearer xxxxx
Content-Type: application/json
resource: 1234
target: https://superwpheroes.io/wp-content/themes/NEGOSOL/_framework/lib/ns-agency-manager/core/integrations/asana/asana-api-php-class-master/examples/test.php
Asana-Fast-Api: true

)

Sent info:
Array
(
    [resource] => 105879108667751
    [target] => https://superwpheroes.io
)
Error while trying to connect to Asana, response code: 400

As you can see, I have tried pushing the 2 parameters into the $headerData array as well but to no success ... same result with or without.
Your help would be greatly appreciated, thank you!

**Comment by ajimix** [comment]
Hello @negosolutions thanks for reporting the issue.
There was a bug with the implementation. Now the problem is fixed and tested (I did a test myself) in the last release `5.1.1`.

Please make sure that your webhook is accessible by Asana via POST, it's https and returns the proper `X-Hook-Secret` header.

If you need more information please read here:
- https://asana.com/developers/api-reference/webhooks
- http://resthooks.org/docs/security/

I'm closing this issue as is now fixed in the latest release.
Please reopen if you still face problems, but as I said, I did a test myself and it worked with the fix 😄

**Comment by negosolutions** [comment]
THANK YOU!
I have edited my issue now for security reasons.
Thanks a million ajimix!

**Comment by negosolutions** [comment]
Ok, this will sound silly... still not working :| I see you updated to version 6.0.0 and I see what you did with the $data thing but it still won't work .... I user your webhook-target.php file as well. Mine was outputing the same thing.
Perhaps maybe you can update the repo with your webhook-create.php file please?
I am using the same token, same workspace id, etc that I use and test with your other methods from the example folder.. created a task, etc, with no issue ... but generating the webhook simply doesn't allow me ... it fails at authentication as

Am I doing something wrong here?

`require_once('../asana.php');

$asana = new Asana(array('personalAccessToken' => 'XXXXXSECURITYRESONS')); 

$target = 'https://nego-solutions.com/asana-api-php-class-master/examples/webhook-target.php';
$workspaceId = 105879108667751;

$asana->createWebhook($workspaceId, $target);

if ($asana->hasError()) {
    echo 'Error while trying to connect to Asana, response code: ' . $asana->responseCode;
    exit;
}

$response = $asana->getData();

echo "getData() response:\n";
echo json_encode($response);`

and I still get this:

Array
(
    [url] => https://app.asana.com/api/1.0/webhooks
    [content_type] => 
    [http_code] => 400
    [header_size] => 0
    [request_size] => 337
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 1.417641
    [namelookup_time] => 0.004208
    [connect_time] => 0.132099
    [pretransfer_time] => 0.40511
    [size_upload] => 135
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 95
    [download_content_length] => -1
    [upload_content_length] => 135
    [starttransfer_time] => 1.417614
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 52.1.223.154
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 84.247.61.4
    [local_port] => 57824
    [request_header] => POST /api/1.0/webhooks HTTP/1.1
Host: app.asana.com
Accept: */*
Authorization: Bearer XXXXXSECURITYRESONS
Content-Type: application/json
Asana-Fast-Api: true
Content-Length: 135


)

Sent info:
{"data":{"resource":105879108667751,"target":"https:\/\/nego-solutions.com\/asana-api-php-class-master\/examples\/webhook-target.php"}}
Error while trying to connect to Asana, response code: 400

maybe if you can update with your webshook generation file then I can just say I am as unlucky as to have done it ok but tried 2 different servers that did not work for whatever reason (SSL or who knows... tho why would the rest of the calls work?).

Thank you!

**Comment by ajimix** [comment]
Hey @negosolutions for my test I've used the same example file I added in the examples folder.
I'm not sure if you can use a workspace ID. I've tested with project ID and the documentation also says the following: `The resource can be a task or project`.
Can you try with a project id instead?

**Comment by ajimix** [comment]
Yes because for querying the webhooks you need to pass the workspace id, but not for creating.

I did another test again on my side, to double check again if it's a problem with the class and it works for me using the following example:

```php
<?php
require_once('../asana.php');

$asana = new Asana(array('personalAccessToken' => 'XXXXXXXXXXX'));

$asana->createWebhook('PROJECT_ID_XXXXXXXXX', 'https://someurl-com'); // The url has the exact same code you can see in examples/webhook-target.php

if ($asana->hasError()) {
    echo 'Error while trying to connect to Asana, response code: ' . $asana->responseCode;
    return;
}
var_dump($asana->getData());
```

And that works and creates the webhook. Note that you can only create a webhook for a project once, so if you run the code again, it will give you back 403 status code.

I did this test with php 7.1.8

Maybe you can try using https localhost as webhook url with this project: https://ngrok.com
That way you will see if Asana is reaching your webhook or not.

Another thing you can do (to see where is the issue) is to call the Asana API directly (without using this PHP class). You can do it using curl. You have an example in the Asana API docs. Here is it:

```
curl -H "Authorization: Bearer <personal_access_token>" \
-X POST https://app.asana.com/api/1.0/webhooks \
-d "resource=8675309" \
-d "target=https://example.com/receive-webhook"```

**Comment by negosolutions** [comment]
Tried that too. Definitely something on my end.
Thank you for your kind support! 
I will investigate further
